name: ControlCheaters
version: 1.0
main: pl.grzegorz2047.controlcheaters.ControlCheaters
commands:
    sprawdz:
        description: Pozwala sprawdzic czy gracz ma aure!
        aliases: [check, spr, ac]